### ISSUE TITLE
Binding Error during start prozess

### ISSUE THREAD

**Issue by Josef69** [csowada/openhab-ebus-binding#7]
Hi,

after a reboot or a Binding update, i get an error every time with the
attached Message. After this error everythink works fine, except the polling time it is lost after a reboot.
Im using the current OH3.0.1 version with a RPI 4 4GB.
[Start Error.txt](https://github.com/csowada/openhab-ebus-binding/files/5889488/Start.Error.txt)

**Comment by csowada** [comment]
Just checked your file, but it looks like the version is fixed on 3.0.0 somewhere in the manifest. I'll check it tomorrow...

**Comment by Josef69** [comment]
Hi, I have done some tests with the polling. The polling registration is missing after a restart, but when I disable and enable a heating thing it is registered again. Like this Log Infos:
[INFO ] [ng.ebus.internal.handler.EBusHandler] - Register polling for "OpModeEffect" every 304 sec. (initial delay 2 sec.) 

I hope it helps you with troubleshooting.

**Comment by Josef69** [comment]
@csowada,

your new update seems to work. Thank's for your quick help.
