### ISSUE TITLE
ebus not working on 3.1.0.M5

### ISSUE THREAD

**Issue by LuiSauberhorn** [csowada/openhab-ebus-binding#9]
Hello csowada,

as discussed in the [community](https://community.openhab.org/t/ebus-2-0-3-0-binding-release-2-50-11-3-0-11/88770/501), I am not able to get ebusd running on OPenhab 3.1.0.M5. System is running on a Debian system on a Pi4. 

As described, I put the binding [kar-file](https://github.com/csowada/openhab-ebus-binding/releases/download/fix001/org.openhab.binding.ebus-3.0.12-SNAPSHOT.kar) and commons-lang-2.6.jar in the add-on folder _/usr/share/openhab/addons_:

```
-rw-r--r-- 1 openhab openhab  284220 Jun 21 23:02 commons-lang-2.6.jar
-rw-r--r-- 1 openhab openhab  734398 Jun 21 23:44 org.openhab.binding.ebus-3.0.12-SNAPSHOT.kar
-rw-r--r-- 1 openhab openhab 2414277 Mär 12 12:41 org.openhab.binding.freeathome-3.1.0-SNAPSHOT.ja
```

Putting the files there does not create any log entry. When I do a _bundle:list_ on karaf console, there is no ebus bundle listed. When I do a

`bundle:install https://github.com/csowada/openhab-ebus-binding/releases/download/fix001/org.openhab.binding.ebus-3.0.12-SNAPSHOT.kar`

I get the following message:
```
Bundle IDs: 
Error executing command: Error installing bundles:
	Unable to install bundle https://github.com/csowada/openhab-ebus-binding/releases/download/fix001/org.openhab.binding.ebus-3.0.12-SNAPSHOT.kar: org.osgi.framework.BundleException: OSGi R3 bundle not supported
```

which seems logical. However, I would have expected that putting the files in the add-in folder works. That at least works for other bindings like free@home (third line above). _bundle:list_ leads to a line:

`236 │ Active │  80 │ 3.1.0.202102081101    │ openHAB Add-ons :: Bundles :: freeathome Binding`

Let me know in case you need more infos.

**Comment by csowada** [comment]
Hello @LuiSauberhorn,

the latest release v3.1.12 should fix the M5 compatibility.

**Comment by LuiSauberhorn** [comment]
New version tested, works fine
